---

- name: "GET STRUCTURED DATA BACK FROM CLI DEVICES"
  hosts: "all"
  connection: "local"
  gather_facts: false

  tasks:

    - name: "GET VLANS IN REAL TIME"
      ntc_show_command:
        connection: "ssh"
        platform: "{{ platform }}"
        command: "{{ vlan_command }}"
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: "result"

    - debug: var=result  # yamllint disable
